apiVersion: v1
kind: Service
metadata:
  name: immich-memories
  namespace: immich-memories
  labels:
    app.kubernetes.io/name: immich-memories
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: immich-memories
