// Every docs URL that existed before the self-hoster refactor (epic #1276),
// mapped to where its text lives now, so links from issues, Reddit and old
// READMEs keep working. A page under being-rewritten/ is the old text kept for
// the PRs that rewrite it: the PR that deletes one points its entry at the
// finished page instead. Never remove an entry.
export const redirects: {from: string; to: string}[] = [
  {from: '/docs/welcome/overview', to: '/docs/'},
  {from: '/docs/welcome/why-immich-memories', to: '/docs/welcome/about'},
  {from: '/docs/create/first-memory', to: '/docs/get-started/first-film'},
  {from: '/docs/create/memory-types', to: '/docs/make/memory-types'},
  {from: '/docs/create/web-ui', to: '/docs/make/web-ui'},
  {from: '/docs/create/titles-and-music', to: '/docs/make/titles-maps-music'},
  {from: '/docs/create/photos-and-live-photos', to: '/docs/make/photos-and-live-photos'},
  {from: '/docs/create/recipes/automated-generation', to: '/docs/make/automate'},
  {from: '/docs/create/cli/generate', to: '/docs/make/cli/generate'},
  {from: '/docs/create/cli/prepare', to: '/docs/make/cli/prepare'},
  {from: '/docs/create/cli/runs', to: '/docs/make/cli/runs'},
  {from: '/docs/deploy/installation/docker', to: '/docs/run/docker'},
  {from: '/docs/deploy/installation/uv-pip', to: '/docs/run/uv-pip'},
  {from: '/docs/deploy/installation/kubernetes', to: '/docs/run/kubernetes'},
  {from: '/docs/deploy/installation/terraform', to: '/docs/run/terraform'},
  {from: '/docs/deploy/configuration/config-file', to: '/docs/run/config-file'},
  {from: '/docs/deploy/configuration/environment-variables', to: '/docs/run/environment-variables'},
  {from: '/docs/deploy/configuration/authentication', to: '/docs/run/authentication'},
  {from: '/docs/deploy/configuration/network-and-privacy', to: '/docs/run/privacy'},
  {from: '/docs/deploy/hardware', to: '/docs/run/hardware'},
  {from: '/docs/deploy/maintenance/health-logs-cache', to: '/docs/run/maintenance/health-logs-cache'},
  {from: '/docs/deploy/maintenance/upgrading', to: '/docs/run/maintenance/upgrading'},
  {from: '/docs/deploy/readers', to: '/docs/better/reader'},
  {from: '/docs/deploy/installation/caption-server', to: '/docs/better/captions'},
  {from: '/docs/deploy/installation/inference-service', to: '/docs/better/inference'},
  {from: '/docs/reference/architecture', to: '/docs/contribute/architecture'},
  {from: '/docs/welcome/built-with-ai', to: '/docs/being-rewritten/built-with-ai'},
  {from: '/docs/create/cli/auto', to: '/docs/being-rewritten/auto'},
  {from: '/docs/create/cli/scheduler', to: '/docs/being-rewritten/scheduler'},
  {from: '/docs/create/pipeline', to: '/docs/being-rewritten/pipeline'},
  {from: '/docs/deploy/running-modes', to: '/docs/being-rewritten/running-modes'},
  {from: '/docs/deploy/self-hosting', to: '/docs/being-rewritten/self-hosting'},
  {from: '/docs/deploy/common-setups/nas-only', to: '/docs/being-rewritten/nas-only'},
  {from: '/docs/deploy/common-setups/mac-local-llm', to: '/docs/being-rewritten/mac-local-llm'},
  {from: '/docs/deploy/common-setups/linux-nvidia', to: '/docs/being-rewritten/linux-nvidia'},
  {from: '/docs/deploy/common-setups/kubernetes-gpu', to: '/docs/being-rewritten/kubernetes-gpu'},
  {from: '/docs/deploy/configuration/editorial-preparation', to: '/docs/being-rewritten/editorial-preparation'},
];
