"""The grandfathered-complexity list is a ratchet, not a bucket.

`make cognitive-complexity` passes when complexipy's snapshot says every
violation was already there. The snapshot is regenerated by the pre-commit hook,
so a change that pushes a function over the limit is silently absolved: the hook
rewrites the file, the gate compares against the rewritten version, and the
allowance grows by one. It reached 36 functions that way, from 13.

This test is the thing that notices. It has no opinion about which functions are
grandfathered -- only that the count cannot climb without someone raising the
number below on purpose, in a commit that says so.
"""

from __future__ import annotations

import json
from pathlib import Path

SNAPSHOT = Path(__file__).resolve().parent.parent / "complexipy-snapshot.json"

# Lower this when the count drops. Never raise it to make a red build green:
# extract a helper instead, which is what the gate is asking for.
MAX_GRANDFATHERED_FUNCTIONS = 35


def test_the_grandfathered_complexity_list_never_grows() -> None:
    entries = json.loads(SNAPSHOT.read_text())
    functions = [f["name"] for entry in entries for f in entry["functions"]]

    assert len(functions) <= MAX_GRANDFATHERED_FUNCTIONS, (
        f"{len(functions)} functions are over the cognitive-complexity limit, "
        f"above the agreed {MAX_GRANDFATHERED_FUNCTIONS}. The snapshot was "
        f"regenerated, which silently widens the allowance. Simplify the new "
        f"offender, or raise MAX_GRANDFATHERED_FUNCTIONS deliberately."
    )
