#!/usr/bin/env python3
"""Write the Remotion demo's fixture module from the hermetic library.

The demo recreates the UI in React over the same pictures the fake Immich
serves, so the two must agree: the thesis, the cut in capture order, the pool
page's first page and its counters. This exports them from
``tests/e2e/fake_library`` into ``docs-site/remotion/src/fixture.ts`` so the
demo cannot drift from the fixture. Run it through ``make demo-fixture``.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tests.e2e.fake_library import (  # noqa: E402
    CARRIERS,
    LIBRARY,
    STORY_OF,
    THESIS,
    pool_line,
    summary_line,
)

from immich_memories.operations.reader_words import stage_words  # noqa: E402

# The pass the fixture's editorial route records its rejections under; the pool
# page prints the reader's words for it, not the engine's name.
DROP_STAGE = "picture_review"

OUT = Path(__file__).resolve().parents[1] / "docs-site" / "remotion" / "src" / "fixture.ts"
MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
POOL_PAGE = 20


def _taken_label(taken_at: str) -> str:
    return f"{MONTHS[int(taken_at[5:7]) - 1]} {taken_at[8:10]} {taken_at[11:16]}"


def _timecodes() -> dict[str, str]:
    """Where each kept picture starts in the cut, in the order the film plays them."""
    at = 0.0
    codes = {}
    for picture in CARRIERS:
        codes[picture.asset_id] = f"{int(at) // 60}:{int(at) % 60:02d}"
        at += picture.seconds
    return codes


def _outcome(picture, timecodes: dict[str, str]) -> str:
    """The line the pool prints under a thumbnail, in CandidateFates' words."""
    if picture.shipped:
        return f"In the cut at {timecodes[picture.asset_id]}: {picture.caption}"
    reason = picture.drop_reason or "not part of any story the month tells"
    return f"Left out at {stage_words(DROP_STAGE)}: {reason}"


def main() -> None:
    shots = []
    previous_month = None
    for picture in CARRIERS:
        month = picture.taken_at[:7]
        shot = {
            "picture": f"library/{picture.source.name}",
            "day": picture.taken_at[:10],
            "motion": picture.is_video,
            "seconds": int(picture.seconds),
            "story": STORY_OF[picture.asset_id].title,
            "reason": picture.caption,
        }
        if month != previous_month:
            shot["chapter"] = f"{MONTHS[int(month[5:7]) - 1]} {month[:4]}".replace("Jun ", "June ")
            previous_month = month
        shots.append(shot)
    timecodes = _timecodes()
    pool = [
        {
            "picture": f"library/{picture.source.name}",
            "motion": picture.is_video,
            "taken": _taken_label(picture.taken_at),
            "file": picture.filename,
            "favourite": picture.is_favorite,
            "ticked": picture.shipped,
            "seconds": int(picture.seconds),
            "outcome": _outcome(picture, timecodes),
        }
        for picture in LIBRARY[:POOL_PAGE]
    ]
    videos = sum(1 for picture in LIBRARY if picture.is_video)
    body = "\n".join(
        [
            "// Generated by scripts/export-demo-fixture.py from tests/e2e/fake_library.py.",
            "// Do not edit: run `make demo-fixture` after the fixture library changes.",
            "",
            "export type Shot = {",
            "  picture: string;",
            "  day: string;",
            "  motion: boolean;",
            "  seconds: number;",
            "  story: string;",
            "  reason: string;",
            "  /** Set on the first picture of a month: the real page prints a chapter label. */",
            "  chapter?: string;",
            "};",
            "",
            "export type PoolCard = {",
            "  picture: string;",
            "  motion: boolean;",
            "  taken: string;",
            "  file: string;",
            "  favourite: boolean;",
            "  ticked: boolean;",
            "  seconds: number;",
            "  /** What the saved cut did with this picture, as the pool page prints it. */",
            "  outcome: string;",
            "};",
            "",
            f"export const THESIS = {json.dumps(THESIS)};",
            f"export const SUMMARY_LINE = {json.dumps(summary_line())};",
            f"export const POOL_LINE = {json.dumps(pool_line())};",
            f"export const POOL_TOTAL = {len(LIBRARY)};",
            f"export const POOL_VIDEOS = {videos};",
            f"export const POOL_PAGE = {POOL_PAGE};",
            f"export const CUT_COUNT = {len(CARRIERS)};",
            f"export const CUT_SECONDS = {int(sum(picture.seconds for picture in CARRIERS))};",
            f"export const SHOTS: Shot[] = {json.dumps(shots, indent=2, ensure_ascii=False)};",
            f"export const POOL: PoolCard[] = {json.dumps(pool, indent=2, ensure_ascii=False)};",
            "",
        ]
    )
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(OUT.parents[3])}: {len(shots)} shots, {len(pool)} pool cards")


if __name__ == "__main__":
    main()
