// Generated by scripts/export-demo-fixture.py from tests/e2e/fake_library.py
// and from docs-site/remotion/public/output-preview.mp4.
// Do not edit: run `make demo-fixture` after the fixture library or the film changes.

export type Shot = {
  picture: string;
  day: string;
  motion: boolean;
  seconds: number;
  start: number;
  story: string;
  reason: string;
  /** Set on the first picture of a month: the real page prints a chapter label. */
  chapter?: string;
};

export type PoolCard = {
  picture: string;
  motion: boolean;
  taken: string;
  file: string;
  favourite: boolean;
  ticked: boolean;
  seconds: number;
  /** What the saved cut did with this picture, as the pool page prints it. */
  outcome: string;
};

export const THESIS = "A month that turns around one birthday afternoon in the garden, spends a Saturday in the woods, and leaves the city for a week camped above a lake before pancakes on the first morning back.";
export const SUMMARY_LINE = "4 stories, 18 pictures";
export const POOL_LINE = "133 in the pool (13 videos, 120 photos)";
export const POOL_TOTAL = 133;
export const POOL_VIDEOS = 13;
export const POOL_PAGE = 20;
export const CUT_COUNT = 18;
export const CUT_SECONDS = 79;
export const CUT_FILM_SECONDS = 61.65000000000001;
export const RECUT_FILM_SECONDS = 61.79999999999999;

/** How long output-preview.mp4 runs, measured. */
export const FILM_SECONDS = 61.57;
/** The last second of it that still shows a photograph, before the ending card. */
export const FILM_PICTURES_END = 54.5;
/** Its size, in the words the completion page prints. */
export const FILM_SIZE = "14 MB";

export const SHOTS: Shot[] = [
  {
    "picture": "library/home-breakfast-01.jpg",
    "day": "2024-06-01",
    "motion": false,
    "seconds": 2.84,
    "start": 3.5,
    "story": "Ordinary days",
    "reason": "the first coffee of the month at the kitchen table",
    "chapter": "June 2024"
  },
  {
    "picture": "library/home-rain-window-01.jpg",
    "day": "2024-06-03",
    "motion": false,
    "seconds": 2.84,
    "start": 5.84,
    "story": "Ordinary days",
    "reason": "rain on the kitchen window, the month's first grey morning"
  },
  {
    "picture": "library/home-dog-walk-01.jpg",
    "day": "2024-06-04",
    "motion": true,
    "seconds": 3.55,
    "start": 8.69,
    "story": "Ordinary days",
    "reason": "the dog pulling towards the park"
  },
  {
    "picture": "library/birthday-balloons-01.jpg",
    "day": "2024-06-08",
    "motion": false,
    "seconds": 2.84,
    "start": 11.74,
    "story": "A birthday in the garden",
    "reason": "balloons tied to the fence before anyone arrived"
  },
  {
    "picture": "library/garden-table.jpg",
    "day": "2024-06-08",
    "motion": true,
    "seconds": 2.84,
    "start": 14.08,
    "story": "A birthday in the garden",
    "reason": "the table and chairs still out on the lawn"
  },
  {
    "picture": "library/garden-cake.jpg",
    "day": "2024-06-08",
    "motion": false,
    "seconds": 2.84,
    "start": 16.43,
    "story": "A birthday in the garden",
    "reason": "the cake with the candles still in it"
  },
  {
    "picture": "library/birthday-candles-01.jpg",
    "day": "2024-06-08",
    "motion": true,
    "seconds": 3.55,
    "start": 19.27,
    "story": "A birthday in the garden",
    "reason": "the candles going out"
  },
  {
    "picture": "library/woods-hamper.jpg",
    "day": "2024-06-15",
    "motion": false,
    "seconds": 2.84,
    "start": 22.82,
    "story": "The Saturday in the woods",
    "reason": "the hamper open on the checked cloth"
  },
  {
    "picture": "library/woods-stream-01.jpg",
    "day": "2024-06-15",
    "motion": false,
    "seconds": 2.84,
    "start": 25.17,
    "story": "The Saturday in the woods",
    "reason": "the stream where the boots came off"
  },
  {
    "picture": "library/woods-path.jpg",
    "day": "2024-06-15",
    "motion": true,
    "seconds": 4.26,
    "start": 28.01,
    "story": "The Saturday in the woods",
    "reason": "the long green path back to the car"
  },
  {
    "picture": "library/home-suitcase-02.jpg",
    "day": "2024-06-21",
    "motion": false,
    "seconds": 2.84,
    "start": 31.77,
    "story": "A week by the lake",
    "reason": "the suitcase open on the bed, the morning we left"
  },
  {
    "picture": "library/trip-lake-arrival-01.jpg",
    "day": "2024-06-21",
    "motion": true,
    "seconds": 3.55,
    "start": 34.62,
    "story": "A week by the lake",
    "reason": "the first sight of the lake from the road down"
  },
  {
    "picture": "library/lake-tents.jpg",
    "day": "2024-06-21",
    "motion": true,
    "seconds": 3.55,
    "start": 37.67,
    "story": "A week by the lake",
    "reason": "the tents pitched on the slope above the lake"
  },
  {
    "picture": "library/trip-morning-mist-01.jpg",
    "day": "2024-06-22",
    "motion": false,
    "seconds": 2.84,
    "start": 40.72,
    "story": "A week by the lake",
    "reason": "mist on the water before anyone else was up"
  },
  {
    "picture": "library/trip-swim-01.jpg",
    "day": "2024-06-22",
    "motion": true,
    "seconds": 3.55,
    "start": 43.07,
    "story": "A week by the lake",
    "reason": "the first swim"
  },
  {
    "picture": "library/lake-sunset.jpg",
    "day": "2024-06-22",
    "motion": false,
    "seconds": 2.84,
    "start": 46.62,
    "story": "A week by the lake",
    "reason": "the last of the sun going down over the water"
  },
  {
    "picture": "library/trip-summit-view-01.jpg",
    "day": "2024-06-23",
    "motion": false,
    "seconds": 2.84,
    "start": 49.46,
    "story": "A week by the lake",
    "reason": "the lake from the top"
  },
  {
    "picture": "library/home-pancakes-01.jpg",
    "day": "2024-06-29",
    "motion": false,
    "seconds": 2.84,
    "start": 51.81,
    "story": "Ordinary days",
    "reason": "pancakes on the first morning back"
  }
];
export const RECUT_SHOTS: Shot[] = [
  {
    "picture": "library/home-rain-window-01.jpg",
    "day": "2024-06-03",
    "motion": false,
    "seconds": 2.98,
    "start": 3.5,
    "story": "Ordinary days",
    "reason": "rain on the kitchen window, the month's first grey morning",
    "chapter": "June 2024"
  },
  {
    "picture": "library/home-dog-walk-01.jpg",
    "day": "2024-06-04",
    "motion": true,
    "seconds": 3.72,
    "start": 6.48,
    "story": "Ordinary days",
    "reason": "the dog pulling towards the park"
  },
  {
    "picture": "library/birthday-balloons-01.jpg",
    "day": "2024-06-08",
    "motion": false,
    "seconds": 2.98,
    "start": 9.7,
    "story": "A birthday in the garden",
    "reason": "balloons tied to the fence before anyone arrived"
  },
  {
    "picture": "library/garden-table.jpg",
    "day": "2024-06-08",
    "motion": true,
    "seconds": 2.98,
    "start": 12.17,
    "story": "A birthday in the garden",
    "reason": "the table and chairs still out on the lawn"
  },
  {
    "picture": "library/garden-cake.jpg",
    "day": "2024-06-08",
    "motion": false,
    "seconds": 2.98,
    "start": 14.65,
    "story": "A birthday in the garden",
    "reason": "the cake with the candles still in it"
  },
  {
    "picture": "library/birthday-candles-01.jpg",
    "day": "2024-06-08",
    "motion": true,
    "seconds": 3.72,
    "start": 17.62,
    "story": "A birthday in the garden",
    "reason": "the candles going out"
  },
  {
    "picture": "library/woods-hamper.jpg",
    "day": "2024-06-15",
    "motion": false,
    "seconds": 2.98,
    "start": 21.34,
    "story": "The Saturday in the woods",
    "reason": "the hamper open on the checked cloth"
  },
  {
    "picture": "library/woods-stream-01.jpg",
    "day": "2024-06-15",
    "motion": false,
    "seconds": 2.98,
    "start": 23.82,
    "story": "The Saturday in the woods",
    "reason": "the stream where the boots came off"
  },
  {
    "picture": "library/woods-path.jpg",
    "day": "2024-06-15",
    "motion": true,
    "seconds": 4.46,
    "start": 26.8,
    "story": "The Saturday in the woods",
    "reason": "the long green path back to the car"
  },
  {
    "picture": "library/home-suitcase-02.jpg",
    "day": "2024-06-21",
    "motion": false,
    "seconds": 2.98,
    "start": 30.76,
    "story": "A week by the lake",
    "reason": "the suitcase open on the bed, the morning we left"
  },
  {
    "picture": "library/trip-lake-arrival-01.jpg",
    "day": "2024-06-21",
    "motion": true,
    "seconds": 3.72,
    "start": 33.74,
    "story": "A week by the lake",
    "reason": "the first sight of the lake from the road down"
  },
  {
    "picture": "library/lake-tents.jpg",
    "day": "2024-06-21",
    "motion": true,
    "seconds": 3.72,
    "start": 36.96,
    "story": "A week by the lake",
    "reason": "the tents pitched on the slope above the lake"
  },
  {
    "picture": "library/trip-morning-mist-01.jpg",
    "day": "2024-06-22",
    "motion": false,
    "seconds": 2.98,
    "start": 40.18,
    "story": "A week by the lake",
    "reason": "mist on the water before anyone else was up"
  },
  {
    "picture": "library/trip-swim-01.jpg",
    "day": "2024-06-22",
    "motion": true,
    "seconds": 3.72,
    "start": 42.65,
    "story": "A week by the lake",
    "reason": "the first swim"
  },
  {
    "picture": "library/lake-sunset.jpg",
    "day": "2024-06-22",
    "motion": false,
    "seconds": 2.98,
    "start": 46.37,
    "story": "A week by the lake",
    "reason": "the last of the sun going down over the water"
  },
  {
    "picture": "library/trip-summit-view-01.jpg",
    "day": "2024-06-23",
    "motion": false,
    "seconds": 2.98,
    "start": 49.35,
    "story": "A week by the lake",
    "reason": "the lake from the top"
  },
  {
    "picture": "library/home-pancakes-01.jpg",
    "day": "2024-06-29",
    "motion": false,
    "seconds": 2.98,
    "start": 51.82,
    "story": "Ordinary days",
    "reason": "pancakes on the first morning back"
  }
];
export const POOL: PoolCard[] = [
  {
    "picture": "library/home-breakfast-01.jpg",
    "motion": false,
    "taken": "Jun 01 08:15",
    "file": "IMG_2401.jpg",
    "favourite": false,
    "ticked": true,
    "seconds": 4,
    "outcome": "In the cut at 0:03: the first coffee of the month at the kitchen table"
  },
  {
    "picture": "library/home-breakfast-02.jpg",
    "motion": false,
    "taken": "Jun 01 08:17",
    "file": "IMG_2402.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 2 minutes later"
  },
  {
    "picture": "library/home-breakfast-03.jpg",
    "motion": false,
    "taken": "Jun 01 08:19",
    "file": "IMG_2403.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 4 minutes later"
  },
  {
    "picture": "library/home-evening-sky-01.jpg",
    "motion": false,
    "taken": "Jun 01 21:30",
    "file": "IMG_2404.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: a sky, and nothing of the family under it"
  },
  {
    "picture": "library/home-park-pond-01.jpg",
    "motion": false,
    "taken": "Jun 02 10:00",
    "file": "IMG_2405.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: the pond, with nobody of ours at it"
  },
  {
    "picture": "library/home-park-pond-02.jpg",
    "motion": false,
    "taken": "Jun 02 10:02",
    "file": "IMG_2406.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 2 minutes later"
  },
  {
    "picture": "library/home-park-pond-03.jpg",
    "motion": false,
    "taken": "Jun 02 10:04",
    "file": "IMG_2407.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 4 minutes later"
  },
  {
    "picture": "library/home-football-lawn-01.jpg",
    "motion": false,
    "taken": "Jun 02 16:00",
    "file": "IMG_2408.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: the ball on the grass, the game already over"
  },
  {
    "picture": "library/home-football-lawn-02.jpg",
    "motion": false,
    "taken": "Jun 02 16:02",
    "file": "IMG_2409.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 2 minutes later"
  },
  {
    "picture": "library/home-rain-window-01.jpg",
    "motion": false,
    "taken": "Jun 03 07:40",
    "file": "IMG_2410.jpg",
    "favourite": false,
    "ticked": true,
    "seconds": 4,
    "outcome": "In the cut at 0:05: rain on the kitchen window, the month's first grey morning"
  },
  {
    "picture": "library/home-rain-window-02.jpg",
    "motion": false,
    "taken": "Jun 03 07:42",
    "file": "IMG_2411.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 2 minutes later"
  },
  {
    "picture": "library/home-rain-window-03.jpg",
    "motion": false,
    "taken": "Jun 03 07:44",
    "file": "IMG_2412.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 4 minutes later"
  },
  {
    "picture": "library/home-kitchen-01.jpg",
    "motion": false,
    "taken": "Jun 03 18:00",
    "file": "IMG_2413.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: a pan on a stove, nothing to say about it"
  },
  {
    "picture": "library/home-kitchen-02.jpg",
    "motion": false,
    "taken": "Jun 03 18:02",
    "file": "IMG_2414.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 2 minutes later"
  },
  {
    "picture": "library/home-kitchen-03.jpg",
    "motion": false,
    "taken": "Jun 03 18:04",
    "file": "IMG_2415.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 4 minutes later"
  },
  {
    "picture": "library/home-desk-laptop-01.jpg",
    "motion": false,
    "taken": "Jun 04 12:30",
    "file": "IMG_2416.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: a laptop on a desk: work, not the household"
  },
  {
    "picture": "library/home-desk-laptop-02.jpg",
    "motion": false,
    "taken": "Jun 04 12:32",
    "file": "IMG_2417.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 2 minutes later"
  },
  {
    "picture": "library/home-desk-laptop-03.jpg",
    "motion": false,
    "taken": "Jun 04 12:34",
    "file": "IMG_2418.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 4 minutes later"
  },
  {
    "picture": "library/home-dog-walk-01.jpg",
    "motion": true,
    "taken": "Jun 04 17:45",
    "file": "IMG_2419.mp4",
    "favourite": false,
    "ticked": true,
    "seconds": 5,
    "outcome": "In the cut at 0:08: the dog pulling towards the park"
  },
  {
    "picture": "library/home-dog-walk-02.jpg",
    "motion": false,
    "taken": "Jun 04 17:47",
    "file": "IMG_2420.jpg",
    "favourite": false,
    "ticked": false,
    "seconds": 4,
    "outcome": "Left out at the picture review: another frame of the same moment, 2 minutes later"
  }
];
